In [3]:
class classroom:
    

SyntaxError: unexpected EOF while parsing (<ipython-input-3-dabb09b25eaa>, line 2)

In [4]:
def test():
    print("test() for function")
    return
test()

test() for function


In [5]:
class demo:
    def test(self):
        print("test() for the  class and method")
        return
obj=demo()
obj.test()
        
    

test() for the  class and method


# factorial

In [1]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)

120

In [3]:
class demo2:
    def accept(self,p1,p2):
        self a=p1
        self b=p2
        return
    def display(self):
        print("a",a)
        print("b",b)
c1=demo2()
c1.accept(10,20)

In [4]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [6]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def mul(self,p1,p2):
        return p1*p2
c1=demo2(10,20)
print(c1.mul(100,200))

20000


In [7]:
# double click to edit

In [9]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(person):
        return True
    
emp=person("chinamy")
print(emp.getname(),emp.isemployee())

emp=employee("rohan")
print(emp.getname(),emp.isemployee())

chinamy False
rohan True


In [20]:
import numpy as np
lst=[1,2,3,4]
a = np.array(lst)
print(a)

[1 2 3 4]


In [21]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [22]:
lst=[1.2,3.5,6.7,6.1]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [26]:
a1=np.array([(1,2,3),(1,2,3)])
print(a1.shape)
a1=np.array([(1,2,3),(1,2,3),(1,2,3)])
print(a1.shape)

(2, 3)
(3, 3)


In [27]:
a1=np.array([(1,2,3),(1,2,3)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [1 2 3]]


array([[1, 2],
       [3, 1],
       [2, 3]])

In [30]:
a1=np.array([(1,2,3)])

a2=np.array([(2,3,4)])
print(np.hstack((a1,a2)))

[[1 2 3 2 3 4]]


In [52]:

a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])


print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [32]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.57009065 5.61128077 4.91747677 5.84460213 4.33357301 6.6828081
 4.96881368 5.38389385 5.27499927 5.20046642]


In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [36]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [37]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [38]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [39]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=14
np.asarray(a)[3][3]=16

print(a)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [45]:


import numpy as np
a=np.matrix(np.ones((3,3),dtype=np.int64))
np.asarray(a)[0][0]=14
np.asarray(a)[2][2]=16
np.asarray(a)[1][1]=0
print(a)
print('sum=',np.asarray(a)[0][0]+np.asarray(a)[2][2]+np.asarray(a)[1][1])


[[14  1  1]
 [ 1  0  1]
 [ 1  1 16]]
sum= 30


In [47]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [49]:
np.arange(2,30,2)
np.arange(1,25,21)

array([ 1, 22])

In [50]:
a1=np.array([(1,2,3),(3,4,5)])
print("slicing coloumn: ",a[:,2])


slicing coloumn:  [[ 1]
 [ 1]
 [16]]


In [51]:
a1=np.array([(1,2,3),(3,4,5)])
print("slicing coloumn: ",a[:,1])
print(a1[0])
print(a1[1])

slicing coloumn:  [[1]
 [0]
 [1]]
[1 2 3]
[3 4 5]


In [53]:
a1=np.random.normal(5,1,10)
print(a1)
print("min val=",np.min(a1))
print("max val=",np.max(a1))
print("mean val=",np.mean(a1))
print("median val=",np.median(a1))


[4.55732402 4.03897841 4.29444393 4.26445364 4.89499533 4.54163865
 8.50540123 4.29994256 5.16633128 5.05005606]
min val= 4.03897841080875
max val= 8.505401231012918
mean val= 4.961356510566569
median val= 4.549481334178955


In [54]:
c1=np.array([1,2])
c2=np.array([3,4])
np.dot(c1,c2)

11

In [56]:
c1=np.array([(1,2),(3,4)])

c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [58]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(1,4),(3,4)])
np.matmul(c1,c2)

array([[ 7, 12],
       [15, 28]])

In [64]:
import pandas as pd
dict={"name":["chinmay","rohan","charith","maneesh"],
     "email id":["chinmaykrishna999@gmail.com","crazyyyrohan8996@gmail.com","iamcharithblue78@gmail.com","iammaneesh1@gmail.com"],
     "mobile number":["9030997968","657643474656","7457657655436","4645757865667"],
     "address":["hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

      name                     email id  mobile number address
0  chinmay  chinmaykrishna999@gmail.com     9030997968     hyd
1    rohan   crazyyyrohan8996@gmail.com   657643474656     hyd
2  charith   iamcharithblue78@gmail.com  7457657655436     hyd
3  maneesh        iammaneesh1@gmail.com  4645757865667     hyd


In [65]:
b.index=["01","02","03","04"]
print(b)

       name                     email id  mobile number address
01  chinmay  chinmaykrishna999@gmail.com     9030997968     hyd
02    rohan   crazyyyrohan8996@gmail.com   657643474656     hyd
03  charith   iamcharithblue78@gmail.com  7457657655436     hyd
04  maneesh        iammaneesh1@gmail.com  4645757865667     hyd


In [67]:
#having least selling percentage 
import pandas as pd
products=pd.read_csv("filename.csv")
print(products)

FileNotFoundError: [Errno 2] File b'filename.csv' does not exist: b'filename.csv'

In [ ]:
import pandas as pd
product.sellingdata=pd.read_csv("filename.csv",index_col +1)
